import '../globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { dir } from 'i18next';
import { languages } from '@/i18n/settings';

const poppins = Poppins({ weight: ['300'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Paulo Paiva Portfolio',
  description: 'Generated by create next app'
};

export async function generateStaticParams() {
  return languages.map((locale) => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale} dir={dir(locale)}>
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
